### ISSUE TITLE
JSX Support

### ISSUE THREAD

**Issue by ryanzec** [LeaVerou/prism#391]
With ReactJS seeming to be getting pretty popular, it would be cool to add support for its JSX syntax.

**Comment by Golmote** [comment]
@ryanzec #479 has been merged.

**Comment by DominicTobias** [comment]
Thanks, has this been released? I npm installed prism and jsx isn't in `prism.languages`?

**Comment by Golmote** [comment]
Yes it's been released. And yes it should highlight your example.
Have you loaded the jsx component? Only a few languages are bundled in the main prism.js file.

**Comment by DominicTobias** [comment]
A right thanks - will see how to do that (I was just doing `import prism from 'prismjs'`

**Comment by iamglenbacs** [comment]
is there a documentation how to integrate this in react? cant seem to find
