### ISSUE TITLE
Extra empty line at the start of the code block

### ISSUE THREAD

**Issue by dandv** [LeaVerou/prism#455]
Looks like prism reads the newline after `<pre><code>` and highlights it. Any way to disable that? In normal usage, we have a newline between `<pre><code>` and the code, and we probably don't want to display it:

```
<pre><code class="language-javascript">
console.log('Hello world');
</code></pre>
```

The output starts with that empty line:

![image](https://cloud.githubusercontent.com/assets/33569/5639548/623ec9e2-95cd-11e4-873e-a5991e4c098c.png)

Of course, I could write
```
<pre><code class="language-javascript">console.log('Hello world');
</code></pre>
```

but that's ugly in the source.

**Comment by vkbansal** [comment]
You can use https://github.com/leeoniya/preCode.js

**Comment by LeaVerou** [comment]
Looks like this is so common we should add it to the Core. It would be as trivial as one call to `.trim()` or one `.replace()`. Is there any legit use case where somebody might *want* a newline in the beginning? @Golmote, thoughts?

**Comment by Golmote** [comment]
IMO, we should replace only one line break at the beginning, if any. (Exactly the behaviour of the `<pre>` tag when it does not contain a `<code>` element, in fact.)

**Comment by haarg** [comment]
This throws off line numbers for things that generate HTML, and also changes the content (not just the visual presentation) compared to how a browser would present represent the markup in the absence of Prism.

For my usage, this means I'll have to add a wrapper to pre-munge the content to add a newline to every highlighted tag before handing it to Prism.

**Comment by LeaVerou** [comment]
I think instead of the `data-manual` attribute, we should support a `data-config` attribute that would accept multiple whitespace-separated tokens to toggle certain things on and off. One of them could be to opt-out of this. Would that be an acceptable solution @haarg ?

**Comment by Golmote** [comment]
I'm not sure I understand your problem, @haarg... Could you give an example?

**Comment by haarg** [comment]
For a code fragment, this change generally will be fine.

One of my use cases though is displaying source files.  In this situation, I need the display to accurately represent what exists in the file, including leading newlines.  The display also needs to be accurate when JavaScript is disabled.  If I add a leading newline in the markup to account for what Prism will strip off, then it will be inaccurately displayed with JavaScript disabled.

**Comment by LeaVerou** [comment]
@haarg makes a good point: The file highlight plugin should somehow disable this behavior, as the accidental new line issue is not present there anyway.

**Comment by vkbansal** [comment]
Why not include this functionality as a plugin?

**Comment by LeaVerou** [comment]
Because it’s functionality that a) requires little code and b) is needed by a very high percentage of our userbase.

**Comment by vkbansal** [comment]
> a) requires little code

`show-language` plugin also has a couple of lines of code.



> b) is needed by a very high percentage of our userbase.

I don't see how it'll harm the users. You certainly have an option to include it at download page. Don't you?

**Comment by LeaVerou** [comment]
Options are not an alternative for sensible defaults. That’s user experience 101.

**Comment by vkbansal** [comment]
Ok. you must know better.

> This throws off line numbers

But not when it breaks your current working code for existing userbase. That software design 101.

**Comment by LeaVerou** [comment]
> But not when it breaks your current working code for existing userbase. That's software design 101.

Depends on how much of an edge case it is, otherwise nothing would ever get fixed because somewhere, someone always depends on that behavior. Common sense 101.

**Comment by Golmote** [comment]
> One of my use cases though is displaying source files. In this situation, I need the display to accurately represent what exists in the file, including leading newlines.

Oh, I get it now... You're perfectly right.

What do you think of @LeaVerou's proposal?

**Comment by Golmote** [comment]
> One of my use cases though is displaying source files. In this situation, I need the display to accurately represent what exists in the file, including leading newlines.

@haarg Oh, I get it now... You're perfectly right. What do you think of @LeaVerou's proposal?

**Comment by LeaVerou** [comment]
The more I think about it, the more I believe that it should be a plug-in that is enabled by default.

--

**Comment by vkbansal** [comment]
> I believe that it should be a plug-in that is enabled by default

Thanks :)

**Comment by LeaVerou** [comment]
> Thanks :)

“Enabled by default” is very different than what you were suggesting.

**Comment by vkbansal** [comment]
My suggestion was a plugin

> Why not include this functionality as a plugin?

Enabling it by default is your choice

**Comment by LeaVerou** [comment]
Gosh, are you always this obnoxious?
Enabling it by default is the crucial part here, as statistically most users tend to go with the defaults. Whether it’s a plugin or an option is secondary.

**Comment by vkbansal** [comment]
And those who do not want it can safely remove the plugin without effecting the core functionality.

Now we are on the same page.

**Comment by haarg** [comment]
Having it as a plugin that can be disabled sounds fine to me.

**Comment by Golmote** [comment]
The removal of the initial line feed has been moved from core to a plugin: http://prismjs.com/plugins/remove-initial-line-feed/

**Comment by LeaVerou** [comment]
Thanks @Golmote! You’re awesome. I have no idea where Prism would be without all your help.

**Comment by omundy** [comment]
This is now located in the normalize whitespace plugin https://prismjs.com/plugins/normalize-whitespace/
