### ISSUE TITLE
Loaded source vs statically defined

### ISSUE THREAD

**Issue by chrisronline** [LeaVerou/prism#458]
Hi,

I'm pulling my hair out over figuring this out. 

`<pre data-src="test2.html"></pre>` works great.

`<pre class="language-markup">
  <code class="language-markup">
   &lt;div&gt;hi&lt;/div&gt;
  </code>
</pre>` does not work great

There is some mysterious padding/margin being added that I can't see in dev tools (I'm hoping I'm just simply missing something simple here)

Fiddle with issue (I don't know how to add files to fiddle so I can't show the working version in the fiddle): http://jsfiddle.net/yw7tk2da/
Here is a screenshot: https://www.dropbox.com/s/r0lckkczqq1r4vp/Screenshot%202015-01-07%2022.20.59.png?dl=0

**Comment by vkbansal** [comment]
It's the expected behavior of the `pre` element. 
http://www.sitepoint.com/everything-need-know-html-pre-element/

You must use the following code
```html
<pre class="language-markup"><code class="language-markup">&lt;div&gt;hi&lt;/div&gt;</code>
</pre>
```

**Comment by chrisronline** [comment]
Makes sense. Thanks so much!
