### ISSUE TITLE
Ordering of inclusion of scripts

### ISSUE THREAD

**Issue by vkbansal** [LeaVerou/prism#463]
When I use the following order
```html
<script src="prism/components/prism-core.js"></script>
<script src="prism/components/prism-markup.js"></script>
<script src="prism/components/prism-clike.js"></script>
<script src="prism/components/prism-javascript.js"></script>
<script src="prism/components/prism-css.js"></script>
```
and looking at `Prism.languages.markup.script.inside.tag.inside` gives
```js
Object {tag: Object, attr-value: Object, punctuation: /\/?>/g, attr-name: Object}
```

But when I include css before js
```html
<script src="prism/components/prism-core.js"></script>
<script src="prism/components/prism-markup.js"></script>
<script src="prism/components/prism-clike.js"></script>
<script src="prism/components/prism-css.js"></script>
<script src="prism/components/prism-javascript.js"></script>
```
`Prism.languages.markup.script.inside.tag.inside` gives
```js
Object {tag: Object, style-attr: Object, attr-value: Object, punctuation: /\/?>/g, attr-name: Object}
```

To summarize, if  CSS is included before JS, `style-attr` gets added to `Prism.languages.markup.script.inside.tag.inside`.

Is it expected behaviour ? Are we supposed to have `style-attr` inside `script`?

**Comment by Golmote** [comment]
If I understand correctly, this is not something we should care about. The case of a `script` tag having a `style` attribute is obviously not common at all. Wether this attribute is highlighted as CSS by Prism or not is not a big deal.

**Comment by vkbansal** [comment]
Thanks, I just needed a clarification. :)
