### ISSUE TITLE
Show invisible plugin does not handle windows line endings well

### ISSUE THREAD

**Issue by vkbansal** [LeaVerou/prism#464]
![capture2](https://cloud.githubusercontent.com/assets/5930351/5692097/aa8be77e-990c-11e4-82a7-54de4acc201e.JPG)

It's get weirder when combined with line-numbers plugin

**Comment by Golmote** [comment]
Feel free to submit a PR if you know how to fix this. I won't be able to take a look before tomorrow night.

Date: Sat, 10 Jan 2015 07:39:04 -0800

**Comment by vkbansal** [comment]
I'm on it. Will let you know as soon as I find some thing.
