### ISSUE TITLE
CORS issue on Website

### ISSUE THREAD

**Issue by mAAdhaTTah** [LeaVerou/prism#473]
I'm seeing this in my console when I visited the website:

```
Font from origin 'http://lea.verou.me' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://prismjs.com' is therefore not allowed access.
```

**Comment by LeaVerou** [comment]
@juliancheal, can we fix this on my server please?

**Comment by vkbansal** [comment]
@LeaVerou http://enable-cors.org/

**Comment by juliancheal** [comment]
Enabled.

curl -I lea.verou.me
HTTP/1.1 200 OK
Date: Thu, 15 Jan 2015 12:08:40 GMT
Server: Apache
X-Powered-By: PHP/5.5.9-1ubuntu4.5
X-Pingback: http://lea.verou.me/xmlrpc.php
Link: <http://wp.me/roQm>; rel=shortlink
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=UTF-8

**Comment by Golmote** [comment]
@mAAdhaTTah Do you confirm this issue is fixed?

**Comment by mAAdhaTTah** [comment]
Yes, sorry, it wasn't at first but I am no longer getting the error.
