### ISSUE TITLE
The Highlight Keywords plugin is 404 when building a customized download

### ISSUE THREAD

**Issue by cookch10** [LeaVerou/prism#490]
When selecting the "Highlight Keywords" plugin, it appears to be 404 and the following error message is shown `An error occurred while fetching the file "plugins/highlight-keywords/prism-highlight-keywords.css".`.  See the following screenshot for details.
![2015-02-04_0936](https://cloud.githubusercontent.com/assets/6051695/6042309/afc2b2d8-ac51-11e4-82ff-f8908e6fab2f.png)

**Comment by Golmote** [comment]
Thanks for reporting!

**Comment by cookch10** [comment]
Thanks for fixing!
