### ISSUE TITLE
C# byte block strange colors

### ISSUE THREAD

**Issue by MaxXor** [LeaVerou/prism#493]
The highlighting of the hex in a byte block is pretty strange if you ask me, it seems to highlight only the ones which contain only numbers for example 0x22 or 0x38. If one letter is in there, it doesn't highlight it.

See this example:
![Strange Colors](https://i.imgur.com/DPbcQTz.png)

**Comment by Golmote** [comment]
Thanks for reporting! This should be fixed now:

![http://puu.sh/fJQ5Z/e82045b5c8.png](http://puu.sh/fJQ5Z/e82045b5c8.png)

**Comment by MaxXor** [comment]
Thanks for fixing!
